import 'package:flutter/material.dart';

class Agent {
  final String slug;
  final String name;
  final String shortName;
  final String category;
  final String description;
  final IconData icon;
  final String brand;
  final int priceCents;
  final String displayPrice;
  final bool active;
  final String setupTime;
  final List<String> capabilities;
  final Color accent;

  const Agent({
    required this.slug,
    required this.name,
    required this.shortName,
    required this.category,
    required this.description,
    required this.icon,
    required this.brand,
    required this.priceCents,
    required this.displayPrice,
    this.active = true,
    this.setupTime = '2 minuti',
    this.capabilities = const [],
    required this.accent,
  });

  double get priceEuro => priceCents / 100;

  static const List<Agent> all = [
    Agent(
      slug: 'shopify-agent',
      name: 'Shopify Agent',
      shortName: 'Shopify',
      category: 'E-commerce & Finance',
      description: 'Cerca prodotti, crea carrelli e verifica ordini e spedizioni 24/7.',
      icon: Icons.shopping_bag_rounded,
      brand: 'shopify',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      setupTime: '2 minuti',
      accent: Color(0xFF95BF47),
      capabilities: ['Ricerca catalogo', 'Link carrello', 'Stato ordine'],
    ),
    Agent(
      slug: 'email-manager',
      name: 'Email Manager',
      shortName: 'Email Manager',
      category: 'Business & Operations',
      description: 'Smista, priorizza e prepara bozze. Tu approvi con un clic.',
      icon: Icons.mail_rounded,
      brand: 'gmail',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      accent: Color(0xFFEA4335),
      capabilities: ['Classifica email', 'Bozze pronte', 'Follow-up'],
    ),
    Agent(
      slug: 'support-agent',
      name: 'Support Agent',
      shortName: 'Support',
      category: 'Customer Service',
      description: 'Risponde a domande su prodotti e ordini 24/7 con FAQ automatiche.',
      icon: Icons.support_agent_rounded,
      brand: 'zendesk',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      accent: Color(0xFF00B8D4),
      capabilities: ['FAQ auto', 'Ordini', 'Resi'],
    ),
    Agent(
      slug: 'lead-capture',
      name: 'Lead Capture',
      shortName: 'Lead Capture',
      category: 'Marketing & Sales',
      description: 'Cattura lead dal sito, arricchisce e avvisa Slack/HubSpot.',
      icon: Icons.filter_alt_rounded,
      brand: 'hubspot',
      priceCents: 499,
      displayPrice: '€4,99/mo',
      accent: Color(0xFFFF6B00),
      capabilities: ['Form → CRM', 'Arricchimento', 'Notifica vendite'],
    ),
    Agent(
      slug: 'calendar-booking',
      name: 'Calendar Booking',
      shortName: 'Calendar',
      category: 'Business & Operations',
      description: 'Propone slot, prenota e invia inviti con reminder automatici.',
      icon: Icons.calendar_month_rounded,
      brand: 'googlecalendar',
      priceCents: 499,
      displayPrice: '€4,99/mo',
      accent: Color(0xFF4285F4),
      capabilities: ['Disponibilità', 'Prenota', 'Reminder'],
    ),
    Agent(
      slug: 'finance-manager',
      name: 'Finance Manager',
      shortName: 'Finance',
      category: 'E-commerce & Finance',
      description: 'Fatture, cashflow da CSV/Stripe e solleciti gentili automatici.',
      icon: Icons.receipt_long_rounded,
      brand: 'stripe',
      priceCents: 1499,
      displayPrice: '€14,99/mo',
      accent: Color(0xFF635BFF),
      capabilities: ['Fatture', 'Incassi', 'Solleciti'],
    ),
    Agent(
      slug: 'seo-agent',
      name: 'SEO Content',
      shortName: 'SEO',
      category: 'Marketing & Sales',
      description: 'Genera contenuti ottimizzati SEO e pianifica il calendario editoriale.',
      icon: Icons.search_rounded,
      brand: 'google',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      accent: Color(0xFF34A853),
      capabilities: ['Articoli SEO', 'Keyword', 'Calendario'],
    ),
    Agent(
      slug: 'copywriter',
      name: 'Copywriter',
      shortName: 'Copywriter',
      category: 'Design & Content',
      description: 'Copy per landing, DEM e social con tono personalizzabile.',
      icon: Icons.edit_note_rounded,
      brand: 'notion',
      priceCents: 799,
      displayPrice: '€7,99/mo',
      accent: Color(0xFF8B5CF6),
      capabilities: ['Landing', 'DEM', 'Social'],
    ),
    Agent(
      slug: 'quote-agent',
      name: 'Preventivi Agent',
      shortName: 'Preventivi',
      category: 'E-commerce & Finance',
      description: 'Raccoglie requisiti e prepara preventivi dettagliati via email.',
      icon: Icons.receipt_long_rounded,
      brand: 'stripe',
      priceCents: 799,
      displayPrice: '€7,99/mo',
      accent: Color(0xFF14B8A6),
      capabilities: ['Requisiti', 'Preventivi', 'Invio email'],
    ),
    Agent(
      slug: 'reviews-agent',
      name: 'Reviews Agent',
      shortName: 'Reviews',
      category: 'Customer Service',
      description: 'Monitora le recensioni Google e prepara risposte professionali.',
      icon: Icons.rate_review_rounded,
      brand: 'google',
      priceCents: 499,
      displayPrice: '€4,99/mo',
      accent: Color(0xFFF59E0B),
      capabilities: ['Monitoraggio', 'Sentiment', 'Risposte'],
    ),
    Agent(
      slug: 'business-manager',
      name: 'Business Manager',
      shortName: 'Business',
      category: 'Business & Operations',
      description: 'Report operativi, KPI e supporto alle decisioni strategiche.',
      icon: Icons.business_center_rounded,
      brand: 'googlesheets',
      priceCents: 1499,
      displayPrice: '€14,99/mo',
      accent: Color(0xFF6366F1),
      capabilities: ['Report', 'KPI', 'Priorità'],
    ),
    Agent(
      slug: 'personal-assistant',
      name: 'Personal Assistant',
      shortName: 'Assistente',
      category: 'Business & Operations',
      description: 'Pianifica le giornate e riassume meeting e note.',
      icon: Icons.person_rounded,
      brand: 'googlecalendar',
      priceCents: 799,
      displayPrice: '€7,99/mo',
      accent: Color(0xFF38BDF8),
      capabilities: ['Agenda', 'Task', 'Riepiloghi'],
    ),
    Agent(
      slug: 'hr-recruiter',
      name: 'HR & Recruiter',
      shortName: 'HR Recruiter',
      category: 'Business & Operations',
      description: 'Screening CV e pianificazione colloqui in automatico.',
      icon: Icons.groups_rounded,
      brand: 'gmail',
      priceCents: 1499,
      displayPrice: '€14,99/mo',
      accent: Color(0xFF3B82F6),
      capabilities: ['Screening CV', 'Matching', 'Colloqui'],
    ),
    Agent(
      slug: 'social-media-agent',
      name: 'Social Media',
      shortName: 'Social',
      category: 'Design & Content',
      description: 'Piano editoriale e caption per Instagram, LinkedIn e TikTok.',
      icon: Icons.campaign_rounded,
      brand: 'instagram',
      priceCents: 799,
      displayPrice: '€7,99/mo',
      accent: Color(0xFFF43F5E),
      capabilities: ['Calendario', 'Caption', 'Hashtag'],
    ),
    Agent(
      slug: 'inventory-logistics',
      name: 'Logistics Agent',
      shortName: 'Logistica',
      category: 'E-commerce & Finance',
      description: 'Scorte, riordini e spedizioni sotto controllo.',
      icon: Icons.inventory_2_rounded,
      brand: 'shopify',
      priceCents: 1499,
      displayPrice: '€14,99/mo',
      accent: Color(0xFFEA580C),
      capabilities: ['Scorte', 'Riordini', 'Spedizioni'],
    ),
    // ─── Prossimamente (stessi del web, non acquistabili da app) ───
    Agent(
      slug: 'email-agent',
      name: 'Email Agent',
      shortName: 'Email Agent',
      category: 'Business & Operations',
      description: 'Legge, classifica e gestisce le email operative in automatico.',
      icon: Icons.email_rounded,
      brand: 'gmail',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      active: false,
      accent: Color(0xFF0EA5E9),
      capabilities: ['Classificazione', 'Risposte AI', 'Escalation'],
    ),
    Agent(
      slug: 'whatsapp-agent',
      name: 'WhatsApp Agent',
      shortName: 'WhatsApp',
      category: 'Customer Service',
      description: 'Conversazioni WhatsApp automatiche: risposte, lead e appuntamenti.',
      icon: Icons.chat_rounded,
      brand: 'whatsapp',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      active: false,
      accent: Color(0xFF25D366),
      capabilities: ['Risposte', 'Lead', 'Appuntamenti'],
    ),
    Agent(
      slug: 'invoice-agent',
      name: 'Invoice Agent',
      shortName: 'Fatture',
      category: 'E-commerce & Finance',
      description: 'Fatture automatiche: generazione, invio e solleciti.',
      icon: Icons.receipt_rounded,
      brand: 'stripe',
      priceCents: 799,
      displayPrice: '€7,99/mo',
      active: false,
      accent: Color(0xFF14B8A6),
      capabilities: ['Fatture', 'Invio', 'Solleciti'],
    ),
    Agent(
      slug: 'analytics-agent',
      name: 'Analytics Agent',
      shortName: 'Analytics',
      category: 'AI & Data',
      description: 'Dai dati alle decisioni: KPI, anomalie e raccomandazioni.',
      icon: Icons.analytics_rounded,
      brand: 'google',
      priceCents: 1499,
      displayPrice: '€14,99/mo',
      active: false,
      accent: Color(0xFF8B5CF6),
      capabilities: ['KPI', 'Anomalie', 'Briefing'],
    ),
    Agent(
      slug: 'crm-agent',
      name: 'CRM Agent',
      shortName: 'CRM',
      category: 'Marketing & Sales',
      description: 'CRM sempre aggiornato: lead, contatti, deal e follow-up.',
      icon: Icons.contacts_rounded,
      brand: 'hubspot',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      active: false,
      accent: Color(0xFFEF4444),
      capabilities: ['Lead', 'Deal', 'Follow-up'],
    ),
    Agent(
      slug: 'document-agent',
      name: 'Document Agent',
      shortName: 'Documenti',
      category: 'AI & Data',
      description: 'Legge PDF, estrae dati e risponde alle domande sui documenti.',
      icon: Icons.description_rounded,
      brand: 'googledrive',
      priceCents: 799,
      displayPrice: '€7,99/mo',
      active: false,
      accent: Color(0xFF78716C),
      capabilities: ['PDF', 'Dati', 'Riassunti'],
    ),
    Agent(
      slug: 'research-agent',
      name: 'Research Agent',
      shortName: 'Research',
      category: 'AI & Data',
      description: 'Ricerche automatiche con fonti verificate e report.',
      icon: Icons.science_rounded,
      brand: 'google',
      priceCents: 999,
      displayPrice: '€9,99/mo',
      active: false,
      accent: Color(0xFF84CC16),
      capabilities: ['Ricerche', 'Confronti', 'Report'],
    ),
  ];

  static Agent? bySlug(String slug) {
    try {
      return all.firstWhere((a) => a.slug == slug);
    } catch (_) {
      return null;
    }
  }
}
